import { product } from "@/components/shop/Mini-Components/CollectionCard"

export const sampleProducts: product[] = [
  {
    _id: "1",
    name: "Velvet Chesterfield Sofa",
    price: 2450,
    image: "/luxury-navy-blue-velvet-chesterfield-sofa-in-elega.jpg",
    subcategory: { name: "Sofas", salePercentage: 0 },
    isXmasDeal: true,
    inStock: true,
    room: "Living Room",
    budgetRange: "premium",
    mood: "Luxurious",
  },
  {
    _id: "2",
    name: "Crystal Cascade Chandelier",
    price: 1890,
    image: "/modern-crystal-chandelier-with-gold-accents-luxury.jpg",
    subcategory: { name: "Chandeliers", salePercentage: 25 },
    isXmasDeal: false,
    inStock: true,
    room: "Dining Room",
    budgetRange: "premium",
    mood: "Luxurious",
  },
  {
    _id: "3",
    name: "Artisan Marble Coffee Table",
    price: 1250,
    image: "/white-marble-coffee-table-with-gold-legs-modern-lu.jpg",
    subcategory: { name: "Tables", salePercentage: 0 },
    isXmasDeal: true,
    inStock: true,
    room: "Living Room",
    budgetRange: "m_id",
    mood: "Luxurious",
  },
  {
    _id: "4",
    name: "Venetian Wall Mirror",
    price: 850,
    image: "/ornate-venetian-gold-frame-wall-mirror-luxury-home.jpg",
    subcategory: { name: "Mirrors", salePercentage: 20 },
    isXmasDeal: false,
    inStock: true,
    room: "Bedroom",
    budgetRange: "m_id",
    mood: "Luxurious",
  },
  {
    _id: "5",
    name: "Abstract Canvas Triptych",
    price: 680,
    image: "/modern-abstract-wall-art-gold-black-cream-three-pa.jpg",
    subcategory: { name: "Wall Art", salePercentage: 15 },
    isXmasDeal: false,
    inStock: true,
    room: "Living Room",
    budgetRange: "budget",
    mood: "Bold",
  },
  {
    _id: "6",
    name: "Silk Throw Pillows Set",
    price: 320,
    image: "/luxury-silk-throw-pillows-cream-gold-embro_idered-d.jpg",
    subcategory: { name: "Textiles", salePercentage: 0 },
    isXmasDeal: true,
    inStock: true,
    room: "Bedroom",
    budgetRange: "budget",
    mood: "Cozy",
  },
  {
    _id: "7",
    name: "Sculptural Floor Lamp",
    price: 1100,
    image: "/modern-sculptural-floor-lamp-brass-black-shade-lux.jpg",
    subcategory: { name: "Lighting", salePercentage: 0 },
    isXmasDeal: false,
    inStock: true,
    room: "Home Office",
    budgetRange: "m_id",
    mood: "Bold",
  },
  {
    _id: "8",
    name: "Hand-Woven Persian Rug",
    price: 3200,
    image: "/luxury-hand-woven-persian-rug-cream-gold-intricate.jpg",
    subcategory: { name: "Rugs", salePercentage: 30 },
    isXmasDeal: true,
    inStock: true,
    room: "Living Room",
    budgetRange: "luxury",
    mood: "Luxurious",
  },
]

export const discountedProducts = sampleProducts.filter(
  (product) => product.isXmasDeal || (product.subcategory.salePercentage && product.subcategory.salePercentage > 0),
)
