export const CATEGORIES = [
  {
    title: "Wall Art",
    image: "/images/Wall art painting in display for sale in an empty room_20250728_045342_0000.jpg",
    description:
    "Blank walls are dead space. Bring them to life with modern, abstract, or luxury framed art that commands attention. Every piece we offer is a conversation starter,because your walls should speak volumes.",
    slug: "wall-art",
  },
  {
    title: "Furniture",
    image: "/images/A couch with a lamp and a table in display for sale in a room_20250728_045608_0000.jpg",
    description:
    "Style meets comfort with our collection of accent chairs, tables, and luxury pieces. These aren’t your average furniture items,they’re interior weapons designed to upgrade your lifestyle and your Instagram feed.",
    slug: "furniture",
  },
  {
    title: "Lighting",
    image: "/images/Image of a chandelier in display for sale_20250728_044852_0000.jpg",
    description:
      "Set the tone of your space with statement lighting that screams elegance. From grand chandeliers to minimalist floor lamps, our curated selection turns any room into a visual experience. Lighting isn't just functional,it's the jewelry of your home.",
    slug: "lighting",
  },
  {
    title: "Greenery",
    image: "/images/A vase filled with flowers_20250728_044627_0000.jpg",
    description:
      "Lush. Alive. Effortless. Our collection of realistic faux plants and elegant planters injects nature’s calm into your space,without the mess or maintenance. It’s green without the grind.",
    slug: "greenery",
  },
  {
    title: "Decorative Objects",
    image: "/images/Home Accessories in display for sale in a room_20250728_045806_0000.jpg",
    description:
      "This is where luxury lives,in the details. Sculptures, vases, trays, and conversation pieces that silently shout taste, power, and precision. If your shelf game isn’t on point, don’t worry,we’ve got the ammo.",
    slug: "decorative-objects",
  },
];

export const CLIENT_REVIEWS = [
  {
    name: "Chioma U.",
    location: "Lekki, Lagos, Nigeria",
    review:
      "The chandelier I got from Geely Home Interiors completely changed my space. It looks expensive, it feels expensive and now, so do I.",
  },
  {
    name: "James H.",
    location: "Brooklyn, New York, USA",
    review:
      "Minimalist but bold. I bought a set of framed wall art and a gold vase, they look like pieces from a gallery. You guys seriously nailed the vibe.",
  },
  {
    name: "Aisha B.",
    location: "Maitama, Abuja, Nigeria",
    review:
      "Your greenery collection is unreal. My office feels like a luxury lounge now. The faux plants look better than real ones.",
  },
  {
    name: "Isabelle M.",
    location: "Paris, France",
    review:
      "I stumbled on Geely Home Interiors through Instagram and ordered two sculptural decor pieces. The craftsmanship is stunning. Delivery to France was smooth too.",
  },
];

export const VALUE_PROPS = [
  {
    title: "Saves You Time",
    description:
      "We’ve already done the hard work of curating timeless, high-impact pieces. No browsing 50 tabs or running to the market, just click, order, and elevate.",
    icon: "🕒", // Replace with SVG or component if needed
  },
  {
    title: "Delivers More Value for Your Money",
    description:
      "Enjoy luxury looks without the luxury price tag. Our pieces offer high-end aesthetics, quality finishes, and long-term use, without breaking the bank.",
    icon: "💸",
  },
  {
    title: "Style Made Simple",
    description:
      "Not sure what matches what? We’ve got you. Every item in our store is handpicked to blend effortlessly, so you can style with confidence, not confusion.",
    icon: "🎯",
  },
  {
    title: "Fast, Safe Nationwide Delivery",
    description:
      "From Lagos to Abuja, Port Harcourt to Kano, we get your order to you safely, securely, and without delays. What you see is what shows up, in one piece.",
    icon: "🚚",
  },
];

  export const Footer_Links = [
    {
      title : "Explore",
      content : [
        "About-Us","Contact","Shipping","Returns","FAQ","Privacy Policy","Terms-of-Service","Cookie-Policy"
      ]
    },
    {
      title : "Categories",
      content : [
        "Living Room","Bedroom","Dinning Room","Office","Lighting","Accessories"
      ]
    }
   ];
  
  export const Header_Menu = [
    {
      name : "Home",
      link : "/"
    },
    {
      name : "Products",
      link : "/shop/products"
    },
    {
      name : "About Us",
      link : "/about-us"
    },
    {
      name : "Contact",
      link : "/contact"
    },
  ]
  
 export const sideMenu = [
    {
      name : "Home",
      link : "/"
    },
    {
      name : "Products",
      link : "/shop/products"
    },
    {
      name : "Wishlist",
      link : "/shop/wishlist"
    },
    {
      name : "Cart",
      link : "/shop/cart"
    },
    {
      name : "Contact",
      link : "/contact"
    },
  ]

 export const products = [
  {
    id: "prod1",
    name: "Modern Velvet Sofa",
    description:
      "Luxurious velvet sofa with a modern design, perfect for any contemporary living room. Features high-density foam cushions and sturdy wooden frame.",
    stock: 20,
    price: 1299.99,
    currency: "USD",
    category: "Living Room",
    categoryId: "1",
    images: [
      "/images/living-room.jpg",
      "/images/white-bedroom.jpg",
      "/images/white-bg.jpg",
    ],
    sku: "SOFA-VEL-MOD-001",
    rating: 4.8,
    reviewsCount: 120,
    features: ["Premium velvet upholstery", "Solid wood frame", "High-resilience foam cushions", "Easy assembly"],
    dimensions: { width: "220 cm", height: "85 cm", depth: "95 cm" },
    colors: ["Grey", "Navy Blue", "Emerald Green"],
  },
  {
    id: "prod2",
    name: "Minimalist Coffee Table",
    description:
      "Sleek and minimalist coffee table made from high-quality tempered glass and polished stainless steel. Adds a touch of elegance to your living area.",
    stock: 20,
    price: 349.5,
    currency: "USD",
    category: "Living Room",
    categoryId: "1",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "TABLE-COF-MIN-002",
    rating: 4.5,
    reviewsCount: 85,
    features: ["Tempered glass top", "Polished stainless steel base", "Scratch-resistant surface", "Easy to clean"],
    dimensions: { width: "100 cm", height: "40 cm", depth: "60 cm" },
    colors: ["Clear", "Smoked Grey"],
  },
  {
    id: "prod3",
    name: "King Size Platform Bed",
    description:
      "Sturdy and stylish king-size platform bed with a tufted headboard. Provides excellent support and a luxurious feel for your bedroom.",
    stock: 20,
    price: 899.0,
    currency: "USD",
    category: "Bedroom",
    categoryId: "2",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "BED-KING-PLT-003",
    rating: 4.9,
    reviewsCount: 210,
    features: ["Tufted velvet headboard", "Solid wood slats", "No box spring required", "Available in multiple sizes"],
    dimensions: { width: "193 cm", height: "120 cm", depth: "210 cm" },
    colors: ["Charcoal", "Beige", "Navy"],
  },
  {
    id: "prod4",
    name: "Industrial Desk Lamp",
    description:
      "Adjustable desk lamp with an industrial design, perfect for home offices or study areas. Features a durable metal construction and a warm light.",
    stock: 20,
    price: 75.0,
    currency: "USD",
    category: "Lighting",
    categoryId: "5",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "LAMP-DESK-IND-004",
    rating: 4.6,
    reviewsCount: 90,
    features: [
      "Adjustable arm and head",
      "Metal construction",
      "E27 bulb compatible (bulb not included)",
      "On/off switch on base",
    ],
    dimensions: { width: "20 cm", height: "50 cm", depth: "20 cm" },
    colors: ["Black", "Bronze"],
  },
  {
    id: "prod5",
    name: "Abstract Wall Art",
    description:
      "Large abstract canvas art piece, hand-painted with vibrant colors. Adds a contemporary focal point to any room.",
    stock: 20,
    price: 250.0,
    currency: "USD",
    category: "Accessories",
    categoryId: "6",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "ART-WALL-ABS-005",
    rating: 4.7,
    reviewsCount: 60,
    features: ["Hand-painted canvas", "Vibrant acrylic colors", "Ready to hang", "Unique design"],
    dimensions: { width: "120 cm", height: "80 cm", depth: "3 cm" },
    colors: ["Multi-color"],
  },
  {
    id: "prod6",
    name: "Ergonomic Office Chair",
    description:
      "High-back ergonomic office chair with adjustable lumbar support, armrests, and headrest. Designed for maximum comfort during long working hours.",
    stock: 20,
    price: 450.0,
    currency: "USD",
    category: "Office",
    categoryId: "4",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "CHAIR-OFF-ERG-006",
    rating: 4.7,
    reviewsCount: 150,
    features: ["Breathable mesh back", "Adjustable height and tilt", "Lumbar support", "Smooth-rolling casters"],
    dimensions: { width: "65 cm", height: "120-130 cm", depth: "60 cm" },
    colors: ["Black", "Grey"],
  },
  {
    id: "prod7",
    name: "Extendable Dining Table",
    description:
      "Modern extendable dining table made from solid oak, perfect for hosting large gatherings. Seats 6-10 people comfortably.",
    stock: 20,
    price: 999.99,
    currency: "USD",
    category: "Dining Room",
    categoryId: "3",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "TABLE-DIN-EXT-007",
    rating: 4.8,
    reviewsCount: 75,
    features: ["Solid oak construction", "Smooth extension mechanism", "Seats 6-10", "Durable finish"],
    dimensions: { width: "160-240 cm", height: "75 cm", depth: "90 cm" },
    colors: ["Natural Oak"],
  },
  {
    id: "prod8",
    name: "Velvet Dining Chairs (Set of 4)",
    description:
      "Set of four elegant velvet dining chairs with sturdy metal legs. Adds a touch of luxury to your dining space.",
    stock: 20,
    price: 599.0,
    currency: "USD",
    category: "Dining Room",
    categoryId: "3",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "CHAIR-DIN-VEL-008",
    rating: 4.6,
    reviewsCount: 110,
    features: ["Soft velvet upholstery", "Powder-coated metal legs", "Ergonomic design", "Easy to assemble"],
    dimensions: { width: "50 cm", height: "85 cm", depth: "55 cm" },
    colors: ["Dark Grey", "Forest Green", "Pink"],
  },
  {
    id: "prod9",
    name: "Geometric Area Rug",
    description:
      "Soft and durable area rug with a modern geometric pattern. Perfect for adding warmth and style to your living room or bedroom.",
    stock: 20,
    price: 180.0,
    currency: "USD",
    category: "Living Room",
    categoryId: "1",
    images: [
      "/images/garden-furniture-6826787_1280.jpg",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "RUG-AREA-GEO-009",
    rating: 4.4,
    reviewsCount: 50,
    features: ["Soft polypropylene fibers", "Non-shedding", "Easy to clean", "Modern geometric design"],
    dimensions: { width: "200 cm", height: "300 cm", depth: "1 cm" },
    colors: ["Grey/White", "Blue/Cream"],
  },
  {
    id: "prod10",
    name: "Smart LED Floor Lamp",
    description:
      "Voice-controlled smart LED floor lamp with adjustable brightness and color temperature. Integrates with smart home systems.",
    stock: 20,
    price: 150.0,
    currency: "USD",
    category: "Lighting",
    categoryId: "5",
    images: [
      "/images/gray-bg.jpg",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "LAMP-FLOOR-SMT-010",
    rating: 4.7,
    reviewsCount: 70,
    features: [
      "Dimmable LED",
      "Color temperature control",
      "Voice control compatible (Alexa, Google Assistant)",
      "Sleek design",
    ],
    dimensions: { width: "25 cm", height: "160 cm", depth: "25 cm" },
    colors: ["Black", "White"],
  },
  {
    id: "prod11",
    name: "Mid-Century Modern Armchair",
    description:
      "Stylish armchair with a solid wood frame and comfortable fabric upholstery, inspired by mid-century design. Perfect for a reading nook.",
    stock: 20,
    price: 499.0,
    currency: "USD",
    category: "Living Room",
    categoryId: "1",
    images: [
      "/images/couch.jpg",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "CHAIR-ARM-MCM-011",
    rating: 4.6,
    reviewsCount: 95,
    features: ["Solid oak frame", "Durable fabric upholstery", "Ergonomic backrest", "Easy to assemble"],
    dimensions: { width: "70 cm", height: "80 cm", depth: "75 cm" },
    colors: ["Teal", "Mustard Yellow", "Grey"],
  },
  {
    id: "prod12",
    name: "Scandi-Style Bookshelf",
    description:
      "Open-concept bookshelf with clean lines and natural wood finish, embodying Scandinavian design principles. Ideal for displaying books and decor.",
    stock: 20,
    price: 280.0,
    currency: "USD",
    category: "Living Room",
    categoryId: "1",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "SHELF-BOOK-SCA-012",
    rating: 4.7,
    reviewsCount: 65,
    features: ["Solid pine wood", "Open shelving", "Easy to clean", "Minimalist design"],
    dimensions: { width: "80 cm", height: "180 cm", depth: "30 cm" },
    colors: ["Natural Wood"],
  },
  {
    id: "prod13",
    name: "Plush Queen Size Mattress",
    description:
      "Premium queen size mattress with memory foam layers for ultimate comfort and support. Reduces motion transfer for undisturbed sleep.",
    stock: 20,
    price: 799.0,
    currency: "USD",
    category: "Bedroom",
    categoryId: "2",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "MATT-QUEEN-PLU-013",
    rating: 4.8,
    reviewsCount: 180,
    features: ["Memory foam comfort", "Medium-firm support", "Hypoallergenic cover", "10-year warranty"],
    dimensions: { width: "152 cm", height: "25 cm", depth: "203 cm" },
    colors: ["White"],
  },
  {
    id: "prod14",
    name: "Bedside Table with Drawer",
    description:
      "Compact bedside table with a single drawer and open shelf, perfect for keeping essentials close at hand. Made from durable MDF with a smooth finish.",
    stock: 20,
    price: 120.0,
    currency: "USD",
    category: "Bedroom",
    categoryId: "2",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "TABLE-BED-DRA-014",
    rating: 4.3,
    reviewsCount: 70,
    features: ["Single smooth-gliding drawer", "Open storage shelf", "Easy to assemble", "Compact design"],
    dimensions: { width: "40 cm", height: "55 cm", depth: "35 cm" },
    colors: ["White", "Black", "Oak"],
  },
  {
    id: "prod15",
    name: "Crystal Chandelier",
    description:
      "Elegant crystal chandelier with multiple tiers, casting a dazzling light. Perfect for dining rooms or grand entryways.",
    stock: 20,
    price: 650.0,
    currency: "USD",
    category: "Lighting",
    categoryId: "5",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "CHAND-CRYS-ELE-015",
    rating: 4.9,
    reviewsCount: 115,
    features: ["High-quality K9 crystals", "Adjustable chain length", "Dimmable (with compatible switch)", "E14 sockets"],
    dimensions: { width: "60 cm", height: "70 cm", depth: "60 cm" },
    colors: ["Clear/Chrome"],
  },
  {
    id: "prod16",
    name: "Abstract Geometric Sculpture",
    description:
      "Modern tabletop sculpture with interlocking geometric shapes, made from polished metal. Adds a contemporary touch to any surface.",
    stock: 20,
    price: 95.0,
    currency: "USD",
    category: "Accessories",
    categoryId: "6",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "SCULPT-GEO-ABS-016",
    rating: 4.5,
    reviewsCount: 40,
    features: ["Polished metal finish", "Stable base", "Unique design", "Tabletop decor"],
    dimensions: { width: "25 cm", height: "30 cm", depth: "15 cm" },
    colors: ["Silver", "Gold"],
  },
  {
    id: "prod17",
    name: "Executive Leather Desk",
    description:
      "Large executive desk with a genuine leather inlay and multiple drawers for ample storage. Ideal for a sophisticated home office.",
    stock: 20,
    price: 1500.0,
    currency: "USD",
    category: "Office",
    categoryId: "4",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "DESK-EXEC-LEA-017",
    rating: 4.8,
    reviewsCount: 80,
    features: ["Genuine leather inlay", "Solid wood construction", "Multiple storage drawers", "Cable management"],
    dimensions: { width: "180 cm", height: "76 cm", depth: "90 cm" },
    colors: ["Dark Walnut", "Black"],
  },
  {
    id: "prod18",
    name: "Modern Dining Chairs (Set of 2)",
    description:
      "Set of two contemporary dining chairs with comfortable upholstered seats and sleek metal legs. Perfect for modern dining spaces.",
    stock: 20,
    price: 299.0,
    currency: "USD",
    category: "Dining Room",
    categoryId: "3",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "CHAIR-DIN-MOD-018",
    rating: 4.5,
    reviewsCount: 70,
    features: ["Upholstered seat", "Powder-coated metal legs", "Ergonomic design", "Easy to assemble"],
    dimensions: { width: "48 cm", height: "82 cm", depth: "52 cm" },
    colors: ["Grey", "Black", "White"],
  },
  {
    id: "prod19",
    name: "Large Faux Fur Throw Blanket",
    description:
      "Luxuriously soft faux fur throw blanket, perfect for adding warmth and texture to your sofa or bed. Generously sized for ultimate comfort.",
    stock: 20,
    price: 85.0,
    currency: "USD",
    category: "Living Room",
    categoryId: "1",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "BLANK-FUR-LRG-019",
    rating: 4.9,
    reviewsCount: 130,
    features: ["Ultra-soft faux fur", "Generous size", "Machine washable", "Adds warmth and style"],
    dimensions: { width: "150 cm", height: "200 cm", depth: "1 cm" },
    colors: ["Cream", "Grey", "Brown"],
  },
  {
    id: "prod20",
    name: "Vintage Style Wall Clock",
    description:
      "Large wall clock with a distressed finish and Roman numerals, adding a touch of vintage charm to any room.",
    stock: 20,
    price: 110.0,
    currency: "USD",
    category: "Accessories",
    categoryId: "6",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "CLOCK-WALL-VIN-020",
    rating: 4.3,
    reviewsCount: 55,
    features: ["Distressed metal frame", "Large Roman numerals", "Silent quartz movement", "Easy to hang"],
    dimensions: { width: "70 cm", height: "70 cm", depth: "4 cm" },
    colors: ["Bronze", "Black"],
  },
  {
    id: "prod21",
    name: "Modular Sectional Sofa",
    description:
      "Highly customizable modular sectional sofa, allowing you to arrange it to fit any living space. Features deep seats and plush cushions.",
    stock: 20,
    price: 2499.0,
    currency: "USD",
    category: "Living Room",
    categoryId: "1",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "SOFA-MOD-SEC-021",
    rating: 4.7,
    reviewsCount: 88,
    features: ["Modular design for flexibility", "Deep, comfortable seating", "Durable fabric", "Easy to reconfigure"],
    dimensions: { width: "300 cm", height: "80 cm", depth: "100 cm" },
    colors: ["Light Grey", "Charcoal", "Beige"],
  },
  {
    id: "prod22",
    name: "Round Marble Coffee Table",
    description:
      "Elegant round coffee table with a genuine marble top and a sturdy metal base. A luxurious centerpiece for your living room.",
    stock: 20,
    price: 580.0,
    currency: "USD",
    category: "Living Room",
    categoryId: "1",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "TABLE-COF-MAR-022",
    rating: 4.9,
    reviewsCount: 72,
    features: ["Genuine marble top", "Powder-coated metal base", "Unique veining", "Easy to clean"],
    dimensions: { width: "90 cm", height: "42 cm", depth: "90 cm" },
    colors: ["White Marble", "Black Marble"],
  },
  {
    id: "prod23",
    name: "Queen Size Storage Bed",
    description:
      "Functional queen size bed with integrated under-bed storage drawers, perfect for maximizing space in smaller bedrooms.",
    stock: 20,
    price: 1100.0,
    currency: "USD",
    category: "Bedroom",
    categoryId: "2",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "BED-QUEEN-STO-023",
    rating: 4.7,
    reviewsCount: 140,
    features: ["Integrated storage drawers", "Sturdy wooden frame", "No box spring needed", "Space-saving design"],
    dimensions: { width: "160 cm", height: "100 cm", depth: "210 cm" },
    colors: ["White", "Grey", "Espresso"],
  },
  {
    id: "prod24",
    name: "Dresser with 6 Drawers",
    description:
      "Spacious dresser with six smooth-gliding drawers, offering ample storage for clothing and linens. Modern design with clean lines.",
    stock: 20,
    price: 550.0,
    currency: "USD",
    category: "Bedroom",
    categoryId: "2",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "DRESS-6DRA-MOD-024",
    rating: 4.6,
    reviewsCount: 90,
    features: ["Six spacious drawers", "Smooth metal glides", "Anti-tip kit included", "Easy to assemble"],
    dimensions: { width: "140 cm", height: "80 cm", depth: "45 cm" },
    colors: ["White", "Black", "Oak"],
  },
  {
    id: "prod25",
    name: "Modern Pendant Light",
    description:
      "Sleek single pendant light with a minimalist design, perfect for kitchen islands or dining areas. Provides focused illumination.",
    stock: 20,
    price: 120.0,
    currency: "USD",
    category: "Lighting",
    categoryId: "5",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "LIGHT-PEND-MOD-025",
    rating: 4.5,
    reviewsCount: 60,
    features: ["Adjustable cord length", "Metal shade", "E26 bulb compatible (not included)", "Easy installation"],
    dimensions: { width: "20 cm", height: "30 cm", depth: "20 cm" },
    colors: ["Black", "White", "Gold"],
  },
  {
    id: "prod26",
    name: "Decorative Ceramic Vase",
    description:
      "Hand-crafted ceramic vase with a unique textured finish, ideal for displaying fresh flowers or as a standalone decorative piece.",
    stock: 20,
    price: 45.0,
    currency: "USD",
    category: "Accessories",
    categoryId: "6",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "VASE-CERA-DEC-026",
    rating: 4.7,
    reviewsCount: 30,
    features: ["Hand-crafted ceramic", "Unique textured finish", "Waterproof interior", "Versatile decor"],
    dimensions: { width: "15 cm", height: "25 cm", depth: "15 cm" },
    colors: ["White", "Terracotta", "Blue"],
  },
  {
    id: "prod27",
    name: "L-Shaped Executive Desk",
    description:
      "Spacious L-shaped executive desk with ample workspace and integrated storage, perfect for a productive home office setup.",
    stock: 20,
    price: 850.0,
    currency: "USD",
    category: "Office",
    categoryId: "4",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "DESK-LSHAPE-EXEC-027",
    rating: 4.6,
    reviewsCount: 65,
    features: ["Large work surface", "Integrated drawers and shelving", "Durable laminate finish", "Reversible configuration"],
    dimensions: { width: "160 cm", height: "75 cm", depth: "140 cm" },
    colors: ["Walnut", "Grey"],
  },
  {
    id: "prod28",
    name: "Round Dining Table (4 Seater)",
    description:
      "Compact round dining table, ideal for small spaces, seating up to 4 people comfortably. Features a sturdy wooden top and metal legs.",
    stock: 20,
    price: 420.0,
    currency: "USD",
    category: "Dining Room",
    categoryId: "3",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "TABLE-DIN-RND-028",
    rating: 4.4,
    reviewsCount: 50,
    features: ["Solid wood top", "Powder-coated metal legs", "Compact design", "Easy to clean"],
    dimensions: { width: "90 cm", height: "75 cm", depth: "90 cm" },
    colors: ["Natural Wood", "Black"],
  },
  {
    id: "prod29",
    name: "Velvet Ottoman with Storage",
    description:
      "Stylish velvet ottoman that doubles as extra seating and hidden storage. Perfect for living rooms or bedrooms.",
    stock: 20,
    price: 180.0,
    currency: "USD",
    category: "Living Room",
    categoryId: "1",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "OTTOMAN-VEL-STO-029",
    rating: 4.7,
    reviewsCount: 70,
    features: ["Soft velvet upholstery", "Hidden storage compartment", "Sturdy construction", "Multi-functional"],
    dimensions: { width: "60 cm", height: "40 cm", depth: "60 cm" },
    colors: ["Emerald Green", "Navy Blue", "Grey"],
  },
  {
    id: "prod30",
    name: "Set of 3 Floating Wall Shelves",
    description:
      "Modern floating wall shelves, perfect for displaying decor, books, or plants. Easy to install and adds a contemporary touch.",
    stock: 20,
    price: 65.0,
    currency: "USD",
    category: "Accessories",
    categoryId: "6",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "SHELF-WALL-FLO-030",
    rating: 4.5,
    reviewsCount: 80,
    features: ["Invisible mounting hardware", "Durable MDF construction", "Easy to install", "Set of three varying sizes"],
    dimensions: { width: "60/45/30 cm", height: "4 cm", depth: "15 cm" },
    colors: ["White", "Black", "Oak"],
  },
  {
    id: "prod31",
    name: "Reclining Leather Sofa",
    description:
      "Luxurious reclining sofa upholstered in genuine leather, offering ultimate comfort and relaxation. Features power recline and adjustable headrests.",
    stock: 20,
    price: 2800.0,
    currency: "USD",
    category: "Living Room",
    categoryId: "1",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "SOFA-REC-LEA-031",
    rating: 4.9,
    reviewsCount: 95,
    features: ["Genuine leather upholstery", "Power recline mechanism", "Adjustable headrests", "USB charging ports"],
    dimensions: { width: "200 cm", height: "100 cm", depth: "95 cm" },
    colors: ["Brown", "Black", "Cream"],
  },
  {
    id: "prod32",
    name: "Glass Top Console Table",
    description:
      "Sleek console table with a tempered glass top and a minimalist metal frame. Perfect for entryways or behind a sofa.",
    stock: 20,
    price: 220.0,
    currency: "USD",
    category: "Living Room",
    categoryId: "1",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "TABLE-CON-GLA-032",
    rating: 4.5,
    reviewsCount: 45,
    features: ["Tempered glass top", "Sturdy metal frame", "Easy to clean", "Slim design"],
    dimensions: { width: "120 cm", height: "75 cm", depth: "30 cm" },
    colors: ["Clear/Black", "Clear/Gold"],
  },
  {
    id: "prod33",
    name: "Adjustable Standing Desk",
    description:
      "Ergonomic standing desk with electric height adjustment, promoting a healthier work posture. Features a spacious desktop and quiet motor.",
    stock: 20,
    price: 600.0,
    currency: "USD",
    category: "Office",
    categoryId: "4",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "DESK-STAND-ADJ-033",
    rating: 4.8,
    reviewsCount: 110,
    features: ["Electric height adjustment", "Memory presets", "Quiet motor", "Spacious desktop"],
    dimensions: { width: "140 cm", height: "70-120 cm", depth: "70 cm" },
    colors: ["Maple", "Black", "White"],
  },
  {
    id: "prod34",
    name: "Bookshelf with Doors",
    description:
      "Versatile bookshelf with open shelves and a lower cabinet with doors, offering both display and concealed storage.",
    stock: 20,
    price: 350.0,
    currency: "USD",
    category: "Office",
    categoryId: "4",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "SHELF-BOOK-DOOR-034",
    rating: 4.6,
    reviewsCount: 75,
    features: ["Adjustable shelves", "Concealed storage cabinet", "Durable laminate finish", "Easy assembly"],
    dimensions: { width: "80 cm", height: "160 cm", depth: "35 cm" },
    colors: ["White", "Espresso"],
  },
  {
    id: "prod35",
    name: "Modern Wall Sconce",
    description:
      "Sleek wall sconce with an integrated LED light, providing ambient illumination. Perfect for hallways, bedrooms, or living rooms.",
    stock: 20,
    price: 90.0,
    currency: "USD",
    category: "Lighting",
    categoryId: "5",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "SCONCE-WALL-MOD-035",
    rating: 4.4,
    reviewsCount: 35,
    features: ["Integrated LED", "Warm white light", "Durable metal construction", "Easy to install"],
    dimensions: { width: "10 cm", height: "30 cm", depth: "10 cm" },
    colors: ["Black", "Gold"],
  },
  {
    id: "prod36",
    name: "Decorative Throw Pillow (Set of 2)",
    description:
      "Set of two soft decorative throw pillows with a unique geometric pattern, perfect for adding comfort and style to your sofa or bed.",
    stock: 20,
    price: 55.0,
    currency: "USD",
    category: "Accessories",
    categoryId: "6",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "PILLOW-THROW-GEO-036",
    rating: 4.7,
    reviewsCount: 60,
    features: ["Soft fabric cover", "Removable insert", "Machine washable cover", "Set of two"],
    dimensions: { width: "45 cm", height: "45 cm", depth: "15 cm" },
    colors: ["Grey/White", "Navy/Cream"],
  },
  {
    id: "prod37",
    name: "Rustic Farmhouse Dining Table",
    description:
      "Solid wood dining table with a distressed finish, bringing a rustic farmhouse charm to your dining area. Seats 6-8 people.",
    stock: 20,
    price: 850.0,
    currency: "USD",
    category: "Dining Room",
    categoryId: "3",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "TABLE-DIN-RUST-037",
    rating: 4.7,
    reviewsCount: 68,
    features: ["Solid reclaimed wood", "Distressed finish", "Sturdy construction", "Seats 6-8"],
    dimensions: { width: "180 cm", height: "76 cm", depth: "90 cm" },
    colors: ["Distressed Brown"],
  },
  {
    id: "prod38",
    name: "Upholstered Dining Bench",
    description:
      "Comfortable upholstered dining bench, perfect for pairing with a dining table or as extra seating in an entryway. Seats 2-3 people.",
    stock: 20,
    price: 320.0,
    currency: "USD",
    category: "Dining Room",
    categoryId: "3",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "BENCH-DIN-UPH-038",
    rating: 4.5,
    reviewsCount: 40,
    features: ["Soft fabric upholstery", "Solid wood legs", "Comfortable padding", "Versatile use"],
    dimensions: { width: "120 cm", height: "45 cm", depth: "40 cm" },
    colors: ["Grey", "Beige", "Navy"],
  },
  {
    id: "prod39",
    name: "Large Decorative Mirror",
    description:
      "Oversized decorative wall mirror with an ornate frame, perfect for adding depth and light to any room.",
    stock: 20,
    price: 280.0,
    currency: "USD",
    category: "Accessories",
    categoryId: "6",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "MIRROR-WALL-LRG-039",
    rating: 4.8,
    reviewsCount: 55,
    features: ["Ornate frame design", "High-quality glass", "Easy to hang", "Adds light and space"],
    dimensions: { width: "90 cm", height: "120 cm", depth: "5 cm" },
    colors: ["Gold", "Silver", "Black"],
  },
  {
    id: "prod40",
    name: "Smart Home Hub",
    description:
      "Central smart home hub that connects and controls all your smart devices, from lighting to thermostats. Voice control enabled.",
    stock: 20,
    price: 199.0,
    currency: "USD",
    category: "Accessories",
    categoryId: "6",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "HUB-SMART-HOME-040",
    rating: 4.6,
    reviewsCount: 100,
    features: ["Voice control (Alexa/Google Assistant)", "Connects multiple devices", "Easy setup", "Intuitive app control"],
    dimensions: { width: "10 cm", height: "5 cm", depth: "10 cm" },
    colors: ["Black", "White"],
  },
  {
    id: "prod41",
    name: "Velvet Accent Chair",
    description:
      "Elegant velvet accent chair with a unique design, perfect for adding a pop of color and luxury to any room.",
    stock: 20,
    price: 380.0,
    currency: "USD",
    category: "Living Room",
    categoryId: "1",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "CHAIR-ACC-VEL-041",
    rating: 4.7,
    reviewsCount: 60,
    features: ["Soft velvet upholstery", "Sturdy metal legs", "Comfortable seating", "Modern design"],
    dimensions: { width: "70 cm", height: "75 cm", depth: "70 cm" },
    colors: ["Royal Blue", "Blush Pink", "Forest Green"],
  },
  {
    id: "prod42",
    name: "Industrial Style TV Stand",
    description:
      "Robust TV stand with a blend of wood and metal, offering an industrial aesthetic. Features open shelving and a cabinet for media storage.",
    stock: 20,
    price: 390.0,
    currency: "USD",
    category: "Living Room",
    categoryId: "1",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "STAND-TV-IND-042",
    rating: 4.5,
    reviewsCount: 70,
    features: ["Solid wood and metal construction", "Open and closed storage", "Cable management cutouts", "Easy assembly"],
    dimensions: { width: "150 cm", height: "50 cm", depth: "40 cm" },
    colors: ["Rustic Brown/Black"],
  },
  {
    id: "prod43",
    name: "Memory Foam Pillow (Set of 2)",
    description:
      "Contour memory foam pillows designed for optimal neck and head support, ensuring a restful night's sleep. Hypoallergenic cover.",
    stock: 20,
    price: 90.0,
    currency: "USD",
    category: "Bedroom",
    categoryId: "2",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "PILLOW-MEM-FOAM-043",
    rating: 4.8,
    reviewsCount: 150,
    features: ["Ergonomic contour design", "Pressure-relieving memory foam", "Hypoallergenic cover", "Machine washable cover"],
    dimensions: { width: "60 cm", height: "12 cm", depth: "40 cm" },
    colors: ["White"],
  },
  {
    id: "prod44",
    name: "Wardrobe with Sliding Doors",
    description:
      "Spacious wardrobe with smooth-gliding sliding doors, perfect for organizing clothes and accessories in any bedroom.",
    stock: 20,
    price: 750.0,
    currency: "USD",
    category: "Bedroom",
    categoryId: "2",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "WARD-SLIDE-DOOR-044",
    rating: 4.6,
    reviewsCount: 80,
    features: ["Smooth sliding doors", "Multiple shelves and hanging rods", "Durable construction", "Space-saving design"],
    dimensions: { width: "180 cm", height: "200 cm", depth: "60 cm" },
    colors: ["White", "Oak"],
  },
  {
    id: "prod45",
    name: "Smart Ceiling Fan with Light",
    description:
      "Modern ceiling fan with integrated LED light and smart control features. Perfect for cooling and illuminating large rooms.",
    stock: 20,
    price: 280.0,
    currency: "USD",
    category: "Lighting",
    categoryId: "5",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "FAN-CEIL-SMT-045",
    rating: 4.7,
    reviewsCount: 90,
    features: ["Integrated LED light", "Remote and app control", "Multiple fan speeds", "Quiet operation"],
    dimensions: { width: "130 cm", height: "30 cm", depth: "130 cm" },
    colors: ["White", "Black"],
  },
  {
    id: "prod46",
    name: "Set of 4 Coasters",
    description:
      "Stylish set of four absorbent coasters, protecting your surfaces from spills and condensation. Features a modern design.",
    stock: 20,
    price: 25.0,
    currency: "USD",
    category: "Accessories",
    categoryId: "6",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "COAST-SET-MOD-046",
    rating: 4.3,
    reviewsCount: 20,
    features: ["Absorbent material", "Non-slip base", "Modern design", "Easy to clean"],
    dimensions: { width: "10 cm", height: "1 cm", depth: "10 cm" },
    colors: ["Grey", "Black", "Marble"],
  },
  {
    id: "prod47",
    name: "Compact Home Office Desk",
    description:
      "Space-saving home office desk with a minimalist design, perfect for small apartments or dedicated work nooks. Features a single drawer.",
    stock: 20,
    price: 180.0,
    currency: "USD",
    category: "Office",
    categoryId: "4",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "DESK-OFF-COMP-047",
    rating: 4.4,
    reviewsCount: 50,
    features: ["Space-saving design", "Single storage drawer", "Durable desktop", "Easy assembly"],
    dimensions: { width: "100 cm", height: "75 cm", depth: "50 cm" },
    colors: ["White", "Oak"],
  },
  {
    id: "prod48",
    name: "Bar Stools (Set of 2)",
    description:
      "Set of two modern bar stools with comfortable upholstered seats and sturdy metal legs. Perfect for kitchen islands or home bars.",
    stock: 20,
    price: 250.0,
    currency: "USD",
    category: "Dining Room",
    categoryId: "3",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "STOOL-BAR-MOD-048",
    rating: 4.6,
    reviewsCount: 65,
    features: ["Upholstered seat", "Powder-coated metal legs", "Footrest for comfort", "Easy to assemble"],
    dimensions: { width: "40 cm", height: "75 cm", depth: "40 cm" },
    colors: ["Grey", "Black", "White"],
  },
  {
    id: "prod49",
    name: "Outdoor Patio Sofa",
    description:
      "Weather-resistant outdoor patio sofa with comfortable cushions, perfect for relaxing in your garden or on your balcony.",
    stock: 20,
    price: 700.0,
    currency: "USD",
    category: "Living Room",
    categoryId: "1",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "SOFA-OUT-PAT-049",
    rating: 4.7,
    reviewsCount: 50,
    features: ["Weather-resistant materials", "UV-protected cushions", "Durable aluminum frame", "Easy to clean"],
    dimensions: { width: "180 cm", height: "70 cm", depth: "80 cm" },
    colors: ["Grey", "Beige"],
  },
  {
    id: "prod50",
    name: "Decorative Floor Lamp",
    description:
      "Tall decorative floor lamp with a unique design and soft ambient light, perfect for adding character to any corner of a room.",
    stock: 20,
    price: 160.0,
    currency: "USD",
    category: "Lighting",
    categoryId: "5",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    sku: "LAMP-FLOOR-DEC-050",
    rating: 4.5,
    reviewsCount: 40,
    features: ["Unique design", "Soft ambient light", "Sturdy base", "Foot switch"],
    dimensions: { width: "30 cm", height: "150 cm", depth: "30 cm" },
    colors: ["Black", "White", "Gold"],
  },
];
